export enum vuexTypes {
  ADD_TODO = "ADD_TODO",
  TOGGLE_ALL_TODO = "TOGGLE_ALL_TODO",
  CHANGE_EDITED_TODO = "CHANGE_EDITED_TODO",
  EDIT_TODO = "EDIT_TODO",
  TOGGLE_TODO_CHECK = "TOGGLE_TODO_CHECK",
  CLEAR_COMPELTED_TODOS = "CLEAR_COMPELTED_TODOS",
  DELETE_TODO = "DELETE_TODO",
}
